### ISSUE TITLE
Implement the Resource Owner Workflow

### ISSUE THREAD

**Issue by gregoryagu** [aurelia-contrib/aurelia-open-id-connect#24]
I really like this plugin.

However, the one thing that is not so good is that there is two complete downloads of Aurelia. First when the user starts the app, and then again, after the user logs in.  

If the "Resource Owner Workflow" were used, then aurelia would get the username/password directly from the user and pass that to the server which would authenticate and pass it back.  Then there is no redirect to an external site, and no second load.

I think this would be a huge improvement.

I am trying to get this going now for a site I am working on.

Or maybe there is a way to detect in main whether or not the user is logged in, and if not, then the user is immediately forwarded before Aurelia bootstraps.

**Comment by shaunluttin** [comment]
Thank you for the comment. I am planning on resuming work on this plugin later this year and will take your feature request into consideration.

**Comment by gerbendekker** [comment]
See this issue on [https://github.com/IdentityModel/oidc-client-js/issues/234](https://github.com/IdentityModel/oidc-client-js/issues/234)

**Comment by arnederuwe** [comment]
Unless oidc-client implements this, this isn't possible as this plugin wraps oidc-client.
There are strong arguments against using the Resource Owner Workflow, so I'm not sure if this will ever get implemented.
