### ISSUE TITLE
Signin redirect does not work in production.

### ISSUE THREAD

**Issue by sreddim** [aurelia-contrib/aurelia-open-id-connect#34]
Hi,
In my application I need to set the signin redirect after the default page is loaded and click on login button from that default page. 

This scenario works on debug mode but not in production.

It works in production only if I do it from app.ts in which case I loose the option to choose between register / login. 
It does not throw any error in production, but it just never redirects and nothing loads in the page.

--app.ts

config.map([
   
   {route: ['', 'login'],   name: 'login',   settings: { icon: 'home' },   moduleId: PLATFORM.moduleName('./login'),   nav: true,   title: 'Home'},
   {route: 'profile',   name: 'profile',   settings: { icon: 'education', auth: true},   moduleId: PLATFORM.moduleName('./profile'),   nav: true,   title: 'Profile'},

]);
this.openIdConnect.configure(config);
   this.config = config;
   this.router = router; 

-->pipeline step:
 config.addPipelineStep('authorize', AuthorizeStep);
 

-->run method from AuthorizeStep:
 async run(navigationInstruction, next) : Promise<boolean>{   

    // currently active route config
    let currentRoute = navigationInstruction.config;
    
    // settings object will be preserved during navigation
    let loginRequired = currentRoute.settings && currentRoute.settings.auth === true;
   
    let user =  await this.openIdConnect.userManager.getUser();
      if (typeof user === undefined || user === null)
          {  
           this.isAuthenticated = false;  
          }
          else
            {
            this.isAuthenticated = true;
            }
    if (this.isAuthenticated === false && loginRequired === true) {
      return next.cancel( this.openIdConnect.userManager.signinRedirect());   
    }   
    return next(this.isAuthenticated);
  }

Could please help me to solve this. Tried to move the login page out from app configrouter and in the main.ts set the root to login.  

 if(app == null || app.user == null)
     {

   aurelia.start().then(() => aurelia.setRoot(PLATFORM.moduleName('login')));
    }
   else
    { 

  aurelia.start().then(() => aurelia.setRoot(PLATFORM.moduleName('app')));
   }

But this approach loads the login page always and after signin and redirect it loads login page 3 times and clicking login 3 times before it goes to my actual profile page which is added as my login redirect.

const oidcConfig: OpenIdConnectConfiguration = {
    loginRedirectModuleId:  PLATFORM.moduleName("./profile"),

works in debug mode. 
![image](https://user-images.githubusercontent.com/33684748/32830887-f07ee2fe-c9f6-11e7-89b6-6fb4b649fc02.png)

not in production.
![image](https://user-images.githubusercontent.com/33684748/32830294-fc46a880-c9f4-11e7-8e07-750db289afd8.png)

**Comment by shaunluttin** [comment]
Have you experimented with the demos here? 

https://github.com/shaunluttin/aurelia-open-id-connect-demos

If you could please reproduce the issue you're experience in a public fork, that would speed up the troubleshooting that I can provide.

**Comment by AndreSteenbergen** [comment]
Have you added the client configuration in the server code for production? It might be the case you allowed your debug environment to communicate with the id server, but not the client on production.

**Comment by sreddim** [comment]
Hi I have client configuration in place. Everything loads in production if I do not have login view included in the app routingconfig and set this as root in main. But the problem is even after login it takes 3 clicks to redirect to to app/profile.
That is the reason I used pipeline step and had all my views(including login) in app configrouter but that does not work in production.

**Comment by shaunluttin** [comment]
There is a chance that protocol switching is the problem. In production, are you using HTTPS for all the pages?

**Comment by sreddim** [comment]
Hi Shaunluttin , Yes my host,  id server, and other api urls everything is using https

**Comment by sreddim** [comment]
Hi Shaunluttin, I will try to recreate using the demos.

**Comment by sreddim** [comment]
Hi, 
the problem is when I publish it in iis as application it does not redirect, but if I publish as a site it is working with all pages in single app router.

I have added web.config with rewrite rule as beloe to resolve the file not found error for static files.
Could this be the reason? or any changes in this would fix it?
Appreciate you suggestion on this.


<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
<rewrite>
             <rules>
                 <remove name="redirect all requests" />
                 <rule name="redirect all requests" stopProcessing="true">
                     <match url="^(.*)$" ignoreCase="false" />
                     <conditions logicalGrouping="MatchAll">
                         <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" ignoreCase="false" />	
			 <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />           
 			  
                     </conditions>
                     <action type="Rewrite" url="/" appendQueryString="true" redirectType="Temporary" />
                 </rule>
             </rules>
         </rewrite> 
    </system.webServer>

**Comment by shaunluttin** [comment]
Apologies for not having responded... I have been away from the computer for a while.

**Comment by arnederuwe** [comment]
Hi, I will be closing up stale issues by the end of the week.

Are you still experiencing this issue? Feel free to close this yourself. If you are still experiencing this issue, let me know as well, thanks!
