### ISSUE TITLE
Login Button Not Show When User Expired

### ISSUE THREAD

**Issue by Cali03** [aurelia-contrib/aurelia-open-id-connect#48]
Hi,

First thank you very much for you job it's a nice plugin.

I don't know if it's a bug or if i am doing something wrong but:

For example i set 40 for accessTokenExpiringNotificationTime and i close the browser when 45s left for the token expire and i open it again when time to expire is 35, the token was not refresh, the manual silent login don't work and when the token was expired the login button don't show because you only check if an user exist.

That only occurs when i sign in whit RememberMe = false if it's set to true work well.

Thanks

**Comment by arnederuwe** [comment]
Hi, I will be closing up stale issues by the end of the week.

Are you still experiencing this issue? Feel free to close this yourself. If you are still experiencing this issue, let me know as well, thanks!
