### ISSUE TITLE
File open-id-connect-user-block.js is not found

### ISSUE THREAD

**Issue by jackiems82** [aurelia-contrib/aurelia-open-id-connect#50]
Sorry to post this here but I currently don't know where to put this as close to this project as possible.

I have a default typescript/.NetCore Aurelia application and are running into the issue that the user-block, user-debug and navigation-filter files cannot be found. I followed the instructions on how to set it up, everything transpiles. But I cannot seem to find the reason why it would not find the files. I hope it is not .NetCore related.

http://localhost:9000/node_modules/aurelia-open-id-connect/dist/amd/open-id-connect-user-block.js 404

Would be great if you would have a hint for me about where I could look to solve this problem.

Best regards

**Comment by jackiems82** [comment]
I glanced through some of your closed issues and found the part where the resources for these files where needed in the aurelia.json at some point and got it working by adding again:

```
"open-id-connect-user-block.html",
"open-id-connect-user-block.js",
 "open-id-connect-user-debug.html",
 "open-id-connect-user-debug.js",
 "open-id-connect-navigation-filter.js"
```

Can you confirm that this is still needed or is there some other issue?

**Comment by shaunluttin** [comment]
As far as I can recall, we no longer need to add those files to aurelia.json file. There is a [demo project here](https://github.com/shaunluttin/aurelia-open-id-connect-demos/tree/master/aurelia-app). Its aurelia.json file does not list those files. There is [another demo project here](https://github.com/shaunluttin/aurelia-open-id-connect-demos/tree/master/aurelia-app-aspnet-core) that is .NET Core specific.

**Comment by gerbendekker** [comment]
> Can you confirm that this is still needed

I'm using typescript+.NET Core+webpack3 but not having this issue.
The demo project is based on the default .NET core SPA template, also worked for me.

**Comment by jackiems82** [comment]
I'm using RequireJs. Maybe that is the issue? I tried with a blank project created with the cli and have the same problems.

**Comment by gerbendekker** [comment]
[Here](https://github.com/gerbendekker/test-aurelia-oidc-cli) is a working test repo using the cli with requirejs + typescript. This is created using the instructions in the readme of this plugin.
I didn't come across an issue.
aurelia cli: 0.32.0
node: 6.9.2
npm 3.10.9

**Comment by jackiems82** [comment]
OK thanks, I will try that again when I find time.

**Comment by davidtimovski** [comment]
jackiems82 is correct. This should be related to #9

**Comment by arnederuwe** [comment]
Hi, I will be closing up stale issues by the end of the week.

Are you still experiencing this issue? Feel free to close this yourself. If you are still experiencing this issue, let me know as well, thanks!
