### ISSUE TITLE
Route "/signin-oidc" don't found in production

### ISSUE THREAD

**Issue by Serfi7** [aurelia-contrib/aurelia-open-id-connect#52]
I have my own idsr app, that works fine and it is published on my IIS server (maybe it dont good idea, but thus I can check how it will work in production).
Also I have my au-app based on AspNetCore.SpaTemplates. But after webpack 4 was released, I modernized this template to work with webpack 4. I spend a lot of time to do this but point was reached. 
After that I connected and set up aurelia-open-id-connect plugin. In debug all works fine. User can authorize and app can do request to API .
But I decided to check how it will work after publish also on my IIS server. And I have one problem:
1. User click button login.
2. User is redirected to idsr app (`app.com/Name/account`).
3. User login there.
4. User is redirected back (`app.com/Name/au-app/Name/au-app/signin-oidc`).
5. Aurelia-router can't found route (`/Name/au-app/signin-oidc`).
![issue](https://user-images.githubusercontent.com/37456151/37542454-4b4708f6-296f-11e8-87d8-6ae1a144c876.png)
Is my oidc plugin config wrong? Is it problem with pushState on IIS (without oidc-plugin routing works fine)?
Also I had tried it with your example ([https://github.com/aurelia-contrib/aurelia-open-id-connect-demos/tree/master/aurelia-app-aspnet-core](url)) but got the same after publishing. In debug all works fine.
![issue-ex](https://user-images.githubusercontent.com/37456151/37543262-10c84390-2972-11e8-9c17-b7cef2458b44.png)

**Comment by Alexander-Taran** [comment]
asked for collective mind help here: https://discourse.aurelia.io/t/challenge-2-help-a-fellow-developer/915

**Comment by gerbendekker** [comment]
mmm,
All I can tell now that ASP.NET+webpack 3.3+Aurelia OIDC works on my machine using a integrated authority.
That means this plugin with pushState works on IIS.
  - What authority are you using?
  - Could you create a repository to have a look at the configs?

![afbeelding](https://user-images.githubusercontent.com/11212123/37557358-92743098-2a03-11e8-849b-f8e6d1d5d08d.png)

**Comment by gerbendekker** [comment]
Also you refer to the demo project, I tested this one also. (Ps the link is not working in your description)
This is a http app combined with [https://demo.identityserver.io](https://demo.identityserver.io) as authority and working in IIS on my machine.

![afbeelding](https://user-images.githubusercontent.com/11212123/37558054-4a539190-2a0e-11e8-9223-00e42df38ddf.png)

**Comment by Serfi7** [comment]
@gerbendekker I published this template combined with [https://demo.identityserver.io](url) as authority. But got the same. [http://drogserj.ddns.net/Nugas/pref](url)

**Comment by gerbendekker** [comment]
I think its a bug where the routes are created by this plugin.
Look at the differences when compare the href `/fetch-data` vs relativeHref `/Nugas/pref/signin-oidc`
@shaunluttin `/Nugas/pref/signin-oidc` should be `/signin-oidc` here.

![afbeelding](https://user-images.githubusercontent.com/11212123/37558905-f8ec1a62-2a1b-11e8-9214-37817e64b39e.png)

**Comment by Serfi7** [comment]
@gerbendekker maybe it don't work because I configured `routerConfig.options.root = "/Nugas/pref";` ? It is necessary for PushState.

**Comment by Serfi7** [comment]
I think I found reason. Method `getPath` return `pathname` of anchor, which have `/Nugas/pref/signin-oidc` value.

![default](https://user-images.githubusercontent.com/37456151/37564563-83f119ae-2aa9-11e8-9717-6b8dfef479f9.png)
![1](https://user-images.githubusercontent.com/37456151/37564592-145e5b0a-2aaa-11e8-9c31-db9e0197140f.png)

**Comment by Serfi7** [comment]
I propose next solution. Aurelia's pushState requeres to set `routerConfiguration.options.root`, which value indicates to tag base. Therefore tag base will always included and it's baseURI will correspond to site URL. 
>                OpenIdConnectRouting.prototype.getPath = function (uri) {
>                 + var anchor = this.convertUriToAnchor(uri);
>                 + var siteUrl= document.getElementsByTagName("base")[0].baseURI;
>                 + console.log(anchor.href.replace(projectUrl, ""));
>                 + return anchor.href.replace(projectUrl, "");
>                };
Is's all changes. What do you think?

**Comment by shaunluttin** [comment]
Thank you for looking in to this. I appreciate it.

**Comment by sreddim** [comment]
Hi, 
I had the similiar problem with system js and webpack when published on IIS

This is because it is trying to read static files.

Use url rewrite to set the redirect paths.

If you have Url rewrite module installed then add this web.config file in the root level of application on production.

If not first install Url rewrite module from microsoft and then add this web.config file.
Once you add the web.config as shown below, the Urlrewrite will pick up the rules set up from the web.config and wont look for static files.


`<configuration>
    <system.webServer>
 

   <rewrite>
             <rules>
                 <remove name="redirect all requests" />
                 <rule name="redirect all requests" stopProcessing="true">
                     <match url="^(.*)$" ignoreCase="false" />
                     <conditions logicalGrouping="MatchAll">
                         <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" pattern="" ignoreCase="false" />	
			 <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />		 
                     </conditions>
                     <action type="Rewrite" url="/" appendQueryString="true" />
                 </rule>
             </rules>
         </rewrite> 
    </system.webServer>
</configuration>`


Hope this helps.

**Comment by arnederuwe** [comment]
Hi, I will be closing up stale issues by the end of the week.

Are you still experiencing this issue? Feel free to close this yourself. If you are still experiencing this issue, let me know as well, thanks!

**Comment by Serfi7** [comment]
I don't use it. So I can't say does it work.
