### ISSUE TITLE
dependency upgrade required

### ISSUE THREAD

**Issue by Alexander-Taran** [aurelia-contrib/aurelia-open-id-connect#53]
![image](https://user-images.githubusercontent.com/1029452/39358059-76f9a016-4a1d-11e8-9e80-b3a0b1794e27.png)
![image](https://user-images.githubusercontent.com/1029452/39358069-81791cf6-4a1d-11e8-8d31-6ee7af46a12f.png)

**Comment by shaunluttin** [comment]
Oddly enough, that warning is not showing up here: https://github.com/aurelia-contrib/aurelia-open-id-connect-demos/network/dependencies

**Comment by Alexander-Taran** [comment]
It does for me (-:

**Comment by shaunluttin** [comment]
The security vulnerability are all fixed, as far as I can tell. Let me know, though, if there is anything that I have missed.
