### ISSUE TITLE
Where is the callback in this sample?

### ISSUE THREAD

**Issue by cosmoKenney** [aurelia-contrib/aurelia-open-id-connect#54]
I'm not great with Aurelia but I'm trying to figure out where the "callback" html page is in this example? I've been reading the code, but haven't build the project yet. 
But I assume that this is implicit flow so at startup this app will redirect the user to the authority's login page. Then the authority redirects back to the "callback" page which should redirect back to the main app entry point page. But I don't see a callback page in this sample.

**Comment by saspeed** [comment]
@cosmoKenney 
You are right in your assumption about the redirect from the authority's login page, 
but there is no callback html to do the redirect. Also the auto redirect is not trivial. 
The implementation adds navigation strategies for each of the redirect routes and an authorize step. 
See: 
- src/open-id-connect-routing.ts: `addLogoutRedirectRoute` and `addLoginRedirectRoute`
- src/open-id-connect-authorize-step.ts: `OpenIdConnectAuthorizeStep` 

Does this answer your question? If so, please close the issue

**Comment by cosmoKenney** [comment]
Thanks!
