### ISSUE TITLE
How to integrate with fetch client

### ISSUE THREAD

**Issue by jackiems82** [aurelia-contrib/aurelia-open-id-connect#57]
Hi, I'm using this plugin and it works really good so far, great work. I have an issue though with the fetch client. When calling a controller method of my api, the authorization header is missing in the request. I guess I need to configure it with the access token from my user but when I debug and check for that info the access token is not set in the user object. Would normally be the access token the one to set in the header? I'm using Bearer authentication.
Is that the general approach to configure the fetch client headers to use that access token or how would that work? Any help is appreciated.

**Comment by Serfi7** [comment]
In docs in Aurelia all are specified. [https://aurelia.io/docs/plugins/http-services#aurelia-fetch-client](url)
At this case:
`this.httpClient.configure(c => c.withDefaults({ headers: { "Authorization": `bearer ${user.access_token}` } }));`

**Comment by jackiems82** [comment]
Thank you for your answer. 
The reason why the access token was undefined in the user object was, a missing **'token'** entry in the _response_type_ in _userManagerSettings_. I changed it like so: `response_type: "id_token token",`

I managed to achieve to get the token in the header like so:
```
.withInterceptor({
    request(request): Promise<Request> {
        return oidc.getUser().then(u => {
            request.headers.append('Authorization', 'Bearer ' + u.access_token);
            return request;
        });
    }
});
```
