### ISSUE TITLE
User Profile Loading even when loadUserProfile is set to false

### ISSUE THREAD

**Issue by phantasm33** [aurelia-contrib/aurelia-open-id-connect#66]
Hi,

I would like to configure the UserManager to not retrieve a user's profile from my IdentityServer. I set loadUserInfo to false, but I am still getting back the user's profile. I download the sample app and trying run it against the demo IdentityServer website and it also retrieves the User's profile information. 

I made no changes to the open-id-connect-configuration-identity-server.ts file:

```
import { OpenIdConnectConfiguration } from "aurelia-open-id-connect";
import { UserManagerSettings, WebStorageStateStore } from "oidc-client";

const appHost = "http://localhost:9000";

export default {
  loginRedirectRoute: "/private",
  logoutRedirectRoute: "/index",
  unauthorizedRedirectRoute: "/index",
  userManagerSettings: {

    // The number of seconds in advance of access token expiry
    // to raise the access token expiring event.
    accessTokenExpiringNotificationTime: 1,

    // Either host your own OpenID Provider or select a certified authority
    // from the list http://openid.net/certification/
    authority: "https://demo.identityserver.io",

    automaticSilentRenew: true,

    // IdentityServer4 supports OpenID Connect Session Management
    // https://openid.net/specs/openid-connect-session-1_0.html
    monitorSession: true,
    checkSessionInterval: 2000,

    // The client or application ID that the authority issues.
    client_id: "implicit",

    filterProtocolClaims: true,
    loadUserInfo: false,
    post_logout_redirect_uri: `${appHost}/signout-oidc`,
    redirect_uri: `${appHost}/signin-oidc`,
    response_type: "id_token",
    scope: "openid email profile",
    // number of millisecods to wait for the authorization
    // server to response to silent renew request
    silentRequestTimeout: 10000,
    silent_redirect_uri: `${appHost}/signin-oidc`,
    userStore: new WebStorageStateStore({
      prefix: "oidc",
      store: window.localStorage,
    }),
  } as UserManagerSettings,
} as OpenIdConnectConfiguration;

```

I modified the main.ts to:
import oidcConfig from "./open-id-connect-configuration-identity-server";

and run the app, signed in as bob, and this is what I got:

> User: {
>   "id_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc2NGNkYzYwMmUyM2E5YjM2MzZjYzE2ZWE1NjRiODdmIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NDYyMDEzOTYsImV4cCI6MTU0NjIwMTY5NiwiaXNzIjoiaHR0cHM6Ly9kZW1vLmlkZW50aXR5c2VydmVyLmlvIiwiYXVkIjoiaW1wbGljaXQiLCJub25jZSI6IjA2ZmE0ZjVlN2YzODQ5OWQ4YmNmMjliNmZiMjQ0YWVkIiwiaWF0IjoxNTQ2MjAxMzk2LCJzaWQiOiJlYzY4YmNmMzE2Yzg5YTRkMjU2MTMzY2I0OTM5YTU0MyIsInN1YiI6Ijg4NDIxMTEzIiwiYXV0aF90aW1lIjoxNTQ2MjAxMzk2LCJpZHAiOiJsb2NhbCIsIm5hbWUiOiJCb2IgU21pdGgiLCJnaXZlbl9uYW1lIjoiQm9iIiwiZmFtaWx5X25hbWUiOiJTbWl0aCIsImVtYWlsIjoiQm9iU21pdGhAZW1haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIndlYnNpdGUiOiJodHRwOi8vYm9iLmNvbSIsImFtciI6WyJwd2QiXX0.dmLr2O_SJQabVGrZO1yRtFCk5gFHX7lSUbK0Vu4lLNh5rpl7ejtPnzXI4_rfPK_3cpQvQfnlKof-vgjkIFVyRhA74H4vru0rTJdNYgKBB9AOMOXZvCPA5pabG6BW72cw6fkd4e2ObI7XsMPll_5Dch-B2C_mrgAdQIUUjGSzJUzQa5fYHm1PzdWjpwkKuHynJCMD8h4pnzg1MMOD4LR6BPOeydMcic3GU8W6AbGv3K0uH1hgqrWFwz6wCEIUVclmYxuZ5jSkxyDATzaTrjeKHHjzK7NyoPVnkErjBZvuREt4x-Yf0dAwGoUyc73VxEx1EehEfkv0ai391QwS-YbJmA",
>   "session_state": "HhLEr7c7kJDreU3c-6VWA4hK5ppAbbMiMjViFasdUBk.1518a23e9a213bacc9b25183fcc221a3",
>   "scope": "openid email profile",
>   "profile": {
>     "sid": "ec68bcf316c89a4d256133cb4939a543",
>     "sub": "88421113",
>     "auth_time": 1546201396,
>     "idp": "local",
>     "name": "Bob Smith",
>     "given_name": "Bob",
>     "family_name": "Smith",
>     "email": "BobSmith@email.com",
>     "email_verified": true,
>     "website": "http://bob.com",
>     "amr": [
>       "pwd"
>     ]
>   }
> }
> 

If I understand the purpose of the loadUserSetting, I should not be seeing any profile information for the user.

Can you please let me know what I am doing wrong. Is there a step that I am missing?

Thanks,
David

**Comment by arnederuwe** [comment]
Hi, I will be closing up stale issues by the end of the week.

Are you still experiencing this issue? Feel free to close this yourself. If you are still experiencing this issue, let me know as well, thanks!
