### ISSUE TITLE
Using this plugin for server side rendering (ssr)?

### ISSUE THREAD

**Issue by andresclaros** [aurelia-contrib/aurelia-open-id-connect#72]
First at all, thank you for your plugin, it is great and easy to user. 

In this moment I want to use in a project that requires server side rendering, and you use Window in OpenIdConnectAuthorizeStep. Is posible to change it for Aurelia's Platform Abstraction Layer Window?

**Comment by arnederuwe** [comment]
It's definitely possible to do that, but it would be the least of your problems I'm afraid..
See this discussion: https://github.com/IdentityModel/oidc-client-js/issues/809
TLDR: don't try to use a client identity model framework on the server, treat them as 2 different clients instead
