### ISSUE TITLE
Document this in the aurelia community if its a valid approach. 

### ISSUE THREAD

**Issue by shaunluttin** [aurelia-contrib/aurelia-open-id-connect#8]
@eisenbergeffect

**Comment by EisenbergEffect** [comment]
This plugin looks pretty solid. One thing I noticed is that it uses some very .NET capitalization in places. I would recommend to follow a more idiomatic JavaScript approach for that.

It looks like there are a few more placeholder bits in there. So, when you think it's ready, let's sync back up. Maybe we can get on Skype and you can do a demo for me. Then I can do a final code review and we can work to put together an article for the community.

**Comment by shaunluttin** [comment]
@EisenbergEffect Time permitting, could you please link a document that describes, or a tslint.json settings collection that specifies, the idiomatic JavaScript capitalization that you are suggesting. That would help me to align the code standards.

**Comment by EisenbergEffect** [comment]
Mainly, I'm referring to property names being lower camel case. For example `foo.firstName` vs. `foo.FirstName`.

**Comment by shaunluttin** [comment]
@EisenbergEffect Thank you. This does it, because it overrides `variable-name` and thereby removes `allow-pascal-case`. 

```
{
  "extends": "tslint:recommended",
  "rules": {
    "variable-name": [
      true,
      "ban-keywords",
      "check-format"
    ]
  }
}
```
https://palantir.github.io/tslint/rules/variable-name/

**Comment by shaunluttin** [comment]
@EisenbergEffect I've correct the property name casing and am moving on to other chores in the code-base. There is a live demo app here: https://zamboni-app.azurewebsites.net/

**Comment by EisenbergEffect** [comment]
Cool! It's code is looking good! Keep me posted. When you are ready, I really want to do a blog post on our official blog about this.

**Comment by shaunluttin** [comment]
@EisenbergEffect Sounds good. I've created a milestone to track issues that we need to complete before documenting this on the official Aurelia blog. I've target to reach that milestone by 31 Dec 2016.

**Comment by mabouchalkha** [comment]
Hi,
good plugin, any progress in this issue.

thank you for this plugin

**Comment by shaunluttin** [comment]
@mabouchalkha There has recently been very little progress on this issue. 

I'm currently contemplating whether to resume work on this plugin or not. 

For me, the benefits to working on it include learning TypeScript, modern JavaScript, OpenID Connect, and a modern front-end framework. Further benefits include engagement with the Aurelia community and a sense of accomplishment, from bringing this plugin to a feature complete 1.0 release. 

The costs me are time, effort, and the discipline to resist the pursuing of other areas of technical interest.

Recently, I have been pursuing the study of algorithms and data structures. The result is that this plugin has taken a backseat to that interest. I have not decided either if or when to resume work on this plugin.

**Comment by shaunluttin** [comment]
@EisenbergEffect I think this is pretty close to ready for a write-up in the Aurelia blog. Please guide me on next steps.

**Comment by EisenbergEffect** [comment]
If you just want to put together a Markdown file for the post and email it to me, that's a good place to start. I'll probably write and introduction for the beginning of that and then we can post it.

**Comment by shaunluttin** [comment]
The blog post is ready here: https://github.com/shaunluttin/aurelia-open-id-connect/tree/aurelia-blog-post.md

**Comment by shaunluttin** [comment]
@EisenbergEffect ^^

**Comment by EisenbergEffect** [comment]
Planning a post this week.
